version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgresmaster}
      POSTGRES_DB: ${POSTGRES_DB_NAME:-FinManagementDb}
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "poetry run python manage.py makemigrations &&
             poetry run python manage.py migrate &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY:-django-insecure-h!p40qmh$m%^ps2vv-t#91ylf250^)p6ga_*2d^yg1h=&2v%lo}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME:-FinManagementDb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgresmaster}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    env_file:
      - .env
    restart: always

volumes:
  postgres_data: